name: Build Spring Boot Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write  # 👈 Required for dependency submission

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install

      - name: Generate Maven Dependency Tree
        run: mvn dependency:tree

      - name: Submit Dependency Graph
        uses: advanced-security/maven-dependency-submission-action@v3
